# Installing Numpy

```pip install numpy```

# Numpy Vs Lists

- Numpy is Faster than list:
    - It uses data of a fixed type so its faster to read less bytes of memory
    - No type checking while iterating through objects
    - Numpy utilizes contigious memory
    - Effetive Cache utilization

# Applications of Numpy
- Mathematics (Replcaement for MATLAB)
- Plotting (Matplotlib)
- Backend (Pandas, Digital Photography)
- Machine Learning


In [2]:
import numpy as np

# The Basics

In [3]:
a=np.array([1,2,3])
# a=np.array([1,2,3],[dtpye=""])
print(a)

[1 2 3]


In [4]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
# Get Dimension
a.ndim

1

In [6]:
# Get SHape
b.shape

(2, 3)

In [7]:
# GET Type
a.dtype

dtype('int32')

In [8]:
#Get Size
a.itemsize

4

In [9]:
# Get Total Size

a.nbytes

12

# Accesing and Changing Specific Elements, Rows , Columns etc

In [10]:
c=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[1 2 3]


In [11]:
# Get specific elements
# a[row,column]

c[1,5]

13

In [12]:
# Get a specif row

c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Get a specfic column

c[:,2]

array([ 3, 10])

In [14]:
#[start,stop,step]
c[0,1:6:2]

array([2, 4, 6])

In [15]:
# Changing

c[1,5]=-c[1,5]
c

array([[  1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12, -13,  14]])

In [16]:
c[:,2]=0
c

array([[  1,   2,   0,   4,   5,   6,   7],
       [  8,   9,   0,  11,  12, -13,  14]])

In [17]:
# Get specif elements in multiple nesting
#works outside in

b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
b[0,1,:]
#same for replacing

array([3, 4])

# Initializing Different Types of Arrays

In [19]:
#All zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
# Any other numbers
np.full((2,3),11)

array([[11, 11, 11],
       [11, 11, 11]])

In [22]:
# Identity Matrix
# just one parameter as it will be a square matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3)
r2=np.repeat(arr,3,axis=0)
print(r1)
print(r2)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


## Replicate this matrix
[
[1,1,1,1,1],
[1,0,0,0,1],
[1,0,9,0,1],
[1,0,0,0,1],
[1,1,1,1,1]
]

In [30]:
a=np.ones((5,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [41]:
b=np.zeros((3,3))
b[1,1]=9
print(b)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [44]:
a[1:-1,1:-1]=b
print(a)

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 9. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [49]:
a[4]=1
a[:,0]=1
a[:,4]=1
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## When we copy make a copy of array directly it will make a shallow copy (just like lists)

So changes made in one will reflect in other

In [50]:
a=np.array([1,2,3])
b=a
b[-1]=100
print(a)

[  1   2 100]


In [51]:
# Hence we use copy function
a=np.array([1,2,3])
b=a.copy()
b[-1]=100
print(a)

[1 2 3]


# Mathematics

In [52]:
a=np.array([1,11,14,44])
a

array([ 1, 11, 14, 44])

In [53]:
a+2

array([ 3, 13, 16, 46])

In [54]:
a*2

array([ 2, 22, 28, 88])

In [55]:
a/2

array([ 0.5,  5.5,  7. , 22. ])

In [56]:
a**2

array([   1,  121,  196, 1936])

In [57]:
a-2

array([-1,  9, 12, 42])

In [58]:
b=np.array([1,2,3,4])
a+b

array([ 2, 13, 17, 48])

In [59]:
# Trigonometry

np.cos(a)

array([0.54030231, 0.0044257 , 0.13673722, 0.99984331])

# Linear Algebra

In [63]:
a=np.ones((2,3))
b=np.full((3,2),2)
print(a,"\n",b)

[[1. 1. 1.]
 [1. 1. 1.]] 
 [[2 2]
 [2 2]
 [2 2]]


In [64]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [66]:
# Determinant
c=np.identity(3)
np.linalg.det(c)

1.0

## We can also find
- Trace
- Eigenvalues
- Inverse Etc

https://docs.scipy.org/reference/routines/linalg.html

# Statistics

In [68]:
s=np.array([[1,2,3],[4,5,6]])

In [70]:
# minimum np.min(array,[axis=0/1])
#same for max

np.min(s,axis=1)

array([1, 4])

In [71]:
np.max(s)

6

In [72]:
np.sum(s)

21

In [73]:
np.mean(s)

3.5

In [75]:
np.median(s)

3.5

# Reorganizing Array

In [78]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
#until the new dimension has same amount of elements as previous one we can reshape it
a.reshape((2,2,2))

[[1 2 3 4]
 [5 6 7 8]]


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [79]:
# Vertically Stacking Vectors

a1=np.array([1,2,3,3])
a2=np.array([5,6,7,8])
np.vstack([a1,a2])

array([[1, 2, 3, 3],
       [5, 6, 7, 8]])

In [80]:
# Horizontal Stacks
np.hstack([a1,a2])

array([1, 2, 3, 3, 5, 6, 7, 8])

# Extra Stuff
(Though we can easily do it in pandas)



In [84]:
# Load data from file
f=np.genfromtxt('data.txt',delimiter=',')
f=f.astype('int32')
f

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

## Boolean Masking and Advanced Indexing

In [85]:
f>4
# data greater than a specfic value

array([[False, False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [86]:
f[f>6]


array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [88]:
np.any(f>100)

False

In [87]:
# Index with a list
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,3,8]]=0
a

array([1, 0, 3, 0, 5, 6, 7, 8, 0])