# Installing Numpy

```pip install numpy```

# Numpy Vs Lists

- Numpy is Faster than list:
    - It uses data of a fixed type so its faster to read less bytes of memory
    - No type checking while iterating through objects
    - Numpy utilizes contigious memory
    - Effetive Cache utilization

# Applications of Numpy
- Mathematics (Replcaement for MATLAB)
- Plotting (Matplotlib)
- Backend (Pandas, Digital Photography)
- Machine Learning


In [7]:
import numpy as np

# The Basics

In [9]:
a=np.array([1,2,3])
# a=np.array([1,2,3],[dtpye=""])
print(a)

[1 2 3]


In [11]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [14]:
# Get Dimension
a.ndim

2

In [13]:
# Get SHape
b.shape

(2, 3)

In [15]:
# GET Type
a.dtype

dtype('int32')

In [16]:
#Get Size
a.itemsize

4

In [17]:
# Get Total Size

a.nbytes

12

# Accesing and Changing Specific Elements, Rows , Columns etc

In [27]:
c=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[list([1, 2, 3, 4, 5, 6, 7]) list([6, 7, 8, 9, 10, 11, 12, 13, 14])]


In [28]:
# Get specific elements
# a[row,column]

c[1,5]

13

In [29]:
# Get a specif row

c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
# Get a specfic column

c[:,2]

array([ 3, 10])

In [31]:
#[start,stop,step]
c[0,1:6:2]

array([2, 4, 6])

In [32]:
# Changing

c[1,5]=-c[1,5]
c

array([[  1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12, -13,  14]])

In [34]:
c[:,2]=0
c

array([[  1,   2,   0,   4,   5,   6,   7],
       [  8,   9,   0,  11,  12, -13,  14]])

In [35]:
# Get specif elements in multiple nesting
#works outside in

b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [36]:
b[0,1,:]
#same for replacing

array([3, 4])

# Initializing Different Types of Arrays

In [37]:
#All zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
# Any other numbers
np.full((2,3),11)

array([[11, 11, 11],
       [11, 11, 11]])